# Generated by Django 5.0.4 on 2024-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={"ordering": ("-timestamp",),},
        ),
        migrations.CreateModel(
            name="PageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("views", models.PositiveIntegerField()),
            ],
            options={"ordering": ("index",),},
        ),
    ]
